# Generated by Django 4.1 on 2022-09-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
