# Generated by Django 4.1 on 2022-08-31 23:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=80)),
                ("slug", models.SlugField(default="Will-be-added")),
            ],
            options={
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=250)),
                ("town", models.CharField(default="", max_length=250)),
                ("bio", ckeditor_uploader.fields.RichTextUploadingField()),
                ("gpsAddress", models.CharField(default="", max_length=50)),
                ("gmapLocation", models.CharField(default="", max_length=250)),
                ("rating", models.IntegerField(max_length=5)),
                ("slug", models.SlugField(default="will-be-added")),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guide.region"
                    ),
                ),
            ],
            options={
                "ordering": ["-rating"],
            },
        ),
    ]
