# Generated by Django 4.1 on 2022-09-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0002_alter_site_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="image",
            field=models.FileField(null=True, upload_to="site_images"),
        ),
    ]
