# Generated by Django 4.1 on 2022-09-02 14:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0003_site_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lodge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("image", models.FileField(null=True, upload_to="lodge_images")),
                ("town", models.CharField(default="", max_length=250)),
                ("bio", ckeditor_uploader.fields.RichTextUploadingField()),
                ("gmapLocation", models.CharField(default="", max_length=250)),
                ("rating", models.IntegerField(default=1, max_length=5)),
                ("slug", models.SlugField(default="will-be-added")),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guide.region"
                    ),
                ),
            ],
            options={
                "ordering": ["-rating"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("town", models.CharField(default="", max_length=250)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guide.region"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
