# Generated by Django 4.1 on 2022-09-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0004_lodge_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.FileField(null=True, upload_to="event_images"),
        ),
    ]
