# Generated by Django 4.1 on 2022-09-04 21:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0005_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="desc",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=""),
        ),
    ]
