# Generated by Django 4.1 on 2022-09-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0006_event_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="saved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lodge",
            name="saved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="site",
            name="saved",
            field=models.BooleanField(default=False),
        ),
    ]
